namespace BlazorNestedCss.Tasks;

public class CssParser
{
    public CssDocument Parse(string css)
    {
        var doc = new CssDocument();

        doc.Tokens.AddRange(Tokenize(css));

        return doc;
    }

    public string Generate(CssDocument root, bool? addPrefix = null)
    {
        if (addPrefix != false)
        {
            root.Tokens.Insert(0, new Token(TokenType.CommentBlock, $"/* CSS Generated by {string.Join(",", GetType().Assembly.FullName.Split(',').Take(2))} */"));
            root.Tokens.Insert(1, new Token(TokenType.Whitespace, "\r\n"));
        }

        return string.Join("", root.Tokens.Select(d => d.Value));
    }

    private IEnumerable<Token> Tokenize(string css)
    {
        var inputReader = new TextStringReader(css);
        var tokenBuilder = new TextStringBuilder();

        while (!inputReader.IsEof())
        {
            if (inputReader.Peek(0) == '/' && inputReader.Peek(1) == '*')
            {
                tokenBuilder.Append(inputReader.Next());
                tokenBuilder.Append(inputReader.Next());
                while (!inputReader.IsEof())
                {
                    var nextChar = inputReader.Next();
                    tokenBuilder.Append(nextChar);
                    if (nextChar == '*' && inputReader.Peek() == '/')
                    {
                        tokenBuilder.Append(inputReader.Next());
                        break;
                    }
                }
            }
            else if (inputReader.Peek(0) == '/' && inputReader.Peek(1) == '/')
            {
                tokenBuilder.Append("/* ");
                tokenBuilder.Append(inputReader.Next());
                tokenBuilder.Append(inputReader.Next());
                while (!inputReader.IsEol(inputReader.Peek()))
                {
                    tokenBuilder.Append(inputReader.Next());
                }
                tokenBuilder.Append(" */");
            }
            else if (inputReader.Peek(0) == '{')
            {
                // Start of a block
                if (tokenBuilder.HasContent())
                    yield return new Token(TokenType.Selector, tokenBuilder.Flush());

                tokenBuilder.Append(inputReader.Next());

                yield return new Token(TokenType.BlockStart, tokenBuilder.Flush());
            }
            else if (inputReader.Peek(0) == '}')
            {
                tokenBuilder.Append(inputReader.Next());

                yield return new Token(TokenType.BlockEnd, tokenBuilder.Flush());
            }
            else if (inputReader.Peek(0) == ';')
            {
                tokenBuilder.Append(inputReader.Next());

                yield return new Token(TokenType.Declaration, tokenBuilder.Flush());
            }
            else if (inputReader.Peek(0) == '"')
            {
                tokenBuilder.Append(inputReader.Next());
                while (!inputReader.IsEof())
                {
                    var nextChar = inputReader.Next();
                    tokenBuilder.Append(nextChar);
                    if (nextChar == '"')
                        break;
                }
            }
            else if (inputReader.Peek(0) == '\'')
            {
                tokenBuilder.Append(inputReader.Next());
                while (!inputReader.IsEof())
                {
                    var nextChar = inputReader.Next();
                    tokenBuilder.Append(nextChar);
                    if (nextChar == '\'')
                        break;
                }
            }
            else if (inputReader.Peek(0) == '(')
            {
                tokenBuilder.Append(inputReader.Next());
                var depth = 1;
                while (!inputReader.IsEof())
                {
                    if (inputReader.Peek(0) == '/' && inputReader.Peek(1) == '*')
                    {
                        tokenBuilder.Append(inputReader.Next()); // consume /
                        tokenBuilder.Append(inputReader.Next()); // consume *
                        while (!inputReader.IsEof())
                        {
                            if (inputReader.Peek(0) == '*' && inputReader.Peek(1) == '/')
                            {
                                tokenBuilder.Append(inputReader.Next()); // consume *
                                tokenBuilder.Append(inputReader.Next()); // consume /
                                break;
                            }
                            tokenBuilder.Append(inputReader.Next());
                        }
                    }
                    else if (inputReader.Peek(0) == '/' && inputReader.Peek(1) == '/')
                    {
                        tokenBuilder.Append("/* ");
                        tokenBuilder.Append(inputReader.Next()); // consume first /
                        tokenBuilder.Append(inputReader.Next()); // consume second /
                        while (!inputReader.IsEol(inputReader.Peek()))
                            tokenBuilder.Append(inputReader.Next());
                        tokenBuilder.Append(" */");
                    }
                    else if (inputReader.Peek(0) == '(')
                    {
                        tokenBuilder.Append(inputReader.Next());
                        depth++;
                    }
                    else if (inputReader.Peek(0) == ')')
                    {
                        tokenBuilder.Append(inputReader.Next());
                        depth--;
                        if (depth == 0)
                            break;
                    }
                    else
                    {
                        tokenBuilder.Append(inputReader.Next());
                    }
                }
            }
            else
            {
                // Part of a selector or declaration
                tokenBuilder.Append(inputReader.Next());
            }
        }

        if (tokenBuilder.HasContent())
            yield return new Token(TokenType.Whitespace, tokenBuilder.Flush());
    }
}
