namespace BlazorNestedCss.Tests;

using BlazorNestedCss.Tasks;

public class BlazorNestedCssRewriterTests
{
    CssParser _parser;
    string prefix;

    public BlazorNestedCssRewriterTests()
    {
        _parser = new CssParser();

        prefix = $"/* CSS Generated by {string.Join(",", _parser.GetType().Assembly.FullName!.Split(',').Take(2))} */\r\n";
    }

    [Fact]
    public void When_Simple_Block_Selectors_CssRewrite_Adds_Scope()
    {
        var cssText = @"
.foo { .bar1, .bar2 { } }
";
        var expected = @"
.foo[b-scope] { .bar1[b-scope], .bar2[b-scope] { } }
";
        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void When_Simple_Block_Selectors_With_Attrs_CssRewrite_Adds_Scope()
    {
        var cssText = @"
.foo[attr] { .bar[attr] [attr] { } }
";
        var expected = @"
.foo[b-scope][attr] { .bar[b-scope][attr] [attr] { } }
";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void When_Simple_Block_Selectors_With_PseudoClass_CssRewrite_Adds_Scope()
    {
        var cssText = @"
.foo:nth-child(2n+1) { }
.foo:has(.sel:not(.bar)) { }
.foo:has(.sel:not(.bar /* */)) { }
";
        // tbody > tr.row:not(:has(td.error)):nth - child(4n + 2 of: not(.hidden)):hover { }
        var expected = @"
.foo[b-scope]:nth-child(2n+1) { }
.foo[b-scope]:has(.sel[b-scope]:not(.bar[b-scope])) { }
.foo[b-scope]:has(.sel[b-scope]:not(.bar[b-scope] /* */)) { }
";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void When_Simple_Block_Selectors_With_Quotes_CssRewrite_Adds_Scope()
    {
        var cssText = @"
    .present-value {
        &::before {
            content: ""(pv: "";
        }

        &::after {
            content :"")"";
        }
    }
";
        // tbody > tr.row:not(:has(td.error)):nth - child(4n + 2 of: not(.hidden)):hover { }
        var expected = @"
    .present-value[b-scope] {
        &::before {
            content: ""(pv: "";
        }

        &::after {
            content :"")"";
        }
    }
";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void When_Deep_Selectors_CssRewrite_Ignores_Scope()
    {
        var cssText = @"
::deep .foo { .bar { &.sel { } } }
.foo { ::deep .bar { &.sel { } } }
.foo {::deep .bar { &.sel { } } }
";
        var expected = @"
.foo { .bar { &.sel { } } }
.foo[b-scope] { .bar { &.sel { } } }
.foo[b-scope] {.bar { &.sel { } } }
";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void When_Deep_Complex_Selectors_CssRewrite_Ignores_Scope()
    {
        var cssText = @"
.foo:has(.sel1)::after ::deep .bar:has(sel2)::after { }
.foo {
    ::deep .bar { table { th.tagme { &.account-name { } } } }
    .bar { ::deep table { th.tagme { &.account-name { } } } }
    .bar { table { th.tagme { &.account-name { } } } } 
}
";
        var expected = @"
.foo[b-scope]:has(.sel1[b-scope])::after .bar:has(sel2)::after { }
.foo[b-scope] {
    .bar { table { th.tagme { &.account-name { } } } }
    .bar[b-scope] { table { th.tagme { &.account-name { } } } }
    .bar[b-scope] { table[b-scope] { th.tagme[b-scope] { &.account-name { } } } } 
}
";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void When_Deep_Multiple_Selectors_CssRewrite_Ignores_Scope()
    {
        var cssText = @"
            .foo1 ::deep input,
            .foo2 input {
                .foo1 input,
                .foo2 input {
                }
            }";

        var expected = @"
            .foo1[b-scope] input,
            .foo2[b-scope] input[b-scope] {
                .foo1 input,
                .foo2 input {
                }
            }";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void When_Deep_Nested_Selectors_CssRewrite_Ignores_Scope()
    {
        var cssText = @"
.foo {
    ::deep .bar { table { th.tagme { ::deep &.account-name { } } } } 
}
";
        var expected = @"
.foo[b-scope] {
    .bar { table { th.tagme { &.account-name { } } } } 
}
";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void When_Comment_Blocks_CssRewrite_Ignores_Content()
    {
        var cssText = @"
.foo { 
    color: blue;
    /* this is a comment line */
    color: blue;
    .bar1 { } /* should get scoped */
    /* this is a comment line */
    .bar2 { } /* should get scoped */
    /* so is this
    .bar3 { }
    */
}";
        var expected = @"
.foo[b-scope] { 
    color: blue;
    /* this is a comment line */
    color: blue;
    .bar1[b-scope] { } /* should get scoped */
    /* this is a comment line */
    .bar2[b-scope] { } /* should get scoped */
    /* so is this
    .bar3 { }
    */
}";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void When_Comment_Blocks_Within_Selectors_CssRewrite_Ignores_Content()
    {
        var cssText = @"
.foo/* this is a selector comment */ { }
.foo/* this is a selector comment .bar */ { }
.foo/* this is a selector comment */.bar/* this is a selector comment */.bar { }
.foo/* this is a selector comment */.bar .bar { }
";
        var expected = @"
.foo[b-scope]/* this is a selector comment */ { }
.foo[b-scope]/* this is a selector comment .bar */ { }
.foo[b-scope]/* this is a selector comment */.bar[b-scope]/* this is a selector comment */.bar[b-scope] { }
.foo[b-scope]/* this is a selector comment */.bar[b-scope] .bar[b-scope] { }
";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void When_Comment_Blocks_Within_Declaration_CssRewrite_Ignores_Content()
    {
        var cssText = @"
.foo {
    /*color: red;
    color: blue;*/
    color: green;
    color/* this is a declaration comment */: blue;
    color: blue/* this is a declaration comment .bar */;
    color: /* this is a declaration comment */ blue;
    animation-name: /* this is a declaration comment */name;
    animation: 1s /* this is a declaration comment */name ease-out forwards;
}
";
        var expected = @"
.foo[b-scope] {
    /*color: red;
    color: blue;*/
    color: green;
    color/* this is a declaration comment */: blue;
    color: blue/* this is a declaration comment .bar */;
    color: /* this is a declaration comment */ blue;
    animation-name: /* this is a declaration comment */name-b-scope;
    animation: 1s /* this is a declaration comment */name-b-scope ease-out forwards;
}
";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void When_Comment_Lines_CssRewrite_Ignores_Content()
    {
        var cssText = @"
.foo { 
    .bar { } // should get scoped
    // this is a comment line .bar { }
    .bar { } // should get scoped
} // and another with no <cr>";
        var expected = @"
.foo[b-scope] { 
    .bar[b-scope] { } /* // should get scoped */
    /* // this is a comment line .bar { } */
    .bar[b-scope] { } /* // should get scoped */
} /* // and another with no <cr> */";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void CssRewrite_Adds_Scope_To_Multiple_Blocks()
    {
        var cssText = @"
.foo {
    .bar1 {
        color: red;
        background-color: blue;
    }

    .bar2 {
        color: yellow;
        background-color: green;
    }
}";
        var expected = @"
.foo[b-scope] {
    .bar1[b-scope] {
        color: red;
        background-color: blue;
    }

    .bar2[b-scope] {
        color: yellow;
        background-color: green;
    }
}";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void CssRewrite_Adds_Scope_To_Complex_Blocks()
    {
        var cssText = @"
.foo {
    prop1: value1;

    .bar1 {
        color: red;
        background-color: blue;
    }

    prop2: value2;

    .bar2 {
        color: yellow;
        background-color: green;
    }

    prop3: value3;
}";
        var expected = @"
.foo[b-scope] {
    prop1: value1;

    .bar1[b-scope] {
        color: red;
        background-color: blue;
    }

    prop2: value2;

    .bar2[b-scope] {
        color: yellow;
        background-color: green;
    }

    prop3: value3;
}";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void CssRewrite_Adds_Scope_To_AtMedia_Blocks()
    {
        var cssText = @"
@media (max-width: 105rem) {
    .card-container {
        grid-template-columns: auto;
    }
}";
        var expected = @"
@media (max-width: 105rem) {
    .card-container[b-scope] {
        grid-template-columns: auto;
    }
}";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void CssRewrite_Adds_Scope_To_AtContainer_Blocks()
    {
        var cssText = @"
@container (max-width: 105rem) {
    .card-container {
        grid-template-columns: auto;
    }
}";
        var expected = @"
@container (max-width: 105rem) {
    .card-container[b-scope] {
        grid-template-columns: auto;
    }
}";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void CssRewrite_Adds_Scope_To_AtKeyframe_Blocks()
    {
        var cssText = @"
@keyframes fadeIn {
    from {
        opacity: 0;
        transform: scale(0.85);
    }

    to {
        opacity: 1;
        transform: scale(1);
    }
}";
        var expected = @"
@keyframes fadeIn-b-scope {
    from {
        opacity: 0;
        transform: scale(0.85);
    }

    to {
        opacity: 1;
        transform: scale(1);
    }
}";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }

    [Fact]
    public void CssRewrite_Adds_Scope_To_Animation_Blocks()
    {
        var cssText = @"
.foo {
    animation-name: name;
    animation-name : name;
    animation-name :name;
    animation-name:name;
    animation-other: name;
    animation: name 1s ease-out forwards;
    animation: 1s name ease-out forwards;
    animation: 1s ease-out name forwards ;
    animation: 1s ease-out forwards name;
    animation: name 1s ease-out forwards , 1s ease-out forwards name;
    animation: name 1s ease-out forwards,1s ease-out forwards name;
    animation: name 1s ease-out forwards, 1s ease-out forwards name;
    animation: name 1s ease-out forwards ,1s ease-out forwards name;
    animation: fade-up var(--duration-slow) var(--ease-spring) both;
    animation-delay: calc(var(--i, 0) * 60ms);
    not-animation: name;
    .animation {
        animation:
            name
            1s
            ease-out
            forwards;
    }
}";
        var expected = @"
.foo[b-scope] {
    animation-name: name-b-scope;
    animation-name : name-b-scope;
    animation-name :name-b-scope;
    animation-name:name-b-scope;
    animation-other: name;
    animation: name-b-scope 1s ease-out forwards;
    animation: 1s name-b-scope ease-out forwards;
    animation: 1s ease-out name-b-scope forwards ;
    animation: 1s ease-out forwards name-b-scope;
    animation: name-b-scope 1s ease-out forwards , 1s ease-out forwards name-b-scope;
    animation: name-b-scope 1s ease-out forwards,1s ease-out forwards name-b-scope;
    animation: name-b-scope 1s ease-out forwards, 1s ease-out forwards name-b-scope;
    animation: name-b-scope 1s ease-out forwards ,1s ease-out forwards name-b-scope;
    animation: fade-up-b-scope var(--duration-slow) var(--ease-spring) both;
    animation-delay: calc(var(--i, 0) * 60ms);
    not-animation: name;
    .animation[b-scope] {
        animation:
            name-b-scope
            1s
            ease-out
            forwards;
    }
}";

        var root = _parser.Parse(cssText);
        new BlazorScopeRewriter().Rewrite(root, "b-scope");
        var output = _parser.Generate(root);

        Assert.Equal(prefix + expected, output);
    }
}
